name: HTML Check
run-name: ${{ github.actor }} is trying HTML Check

on:
  push:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 # Requried will all actions
    - name: Checks HTML5
      uses: Cyb3r-Jak3/html5validator-action@<latest version>
      with:
        root: test.html

    - name: HTML5 Validator
      uses: Cyb3r-Jak3/html5validator-action@v7.1.1
